version: '3.7'

services:
  iris:
    image: store/intersystems/iris-community:2020.2.0.211.0
    init: true
    environment: 
      ISC_DATA_DIRECTORY: /opt/config/iris
    volumes:
      - config:/opt/config
    ports:
      - 52773
  web:
    build: .
    init: true
    ports:
      - 80:80
    environment: 
      SERVER_HOST: iris
      SERVER_PORT: 51773
volumes:
  config: 